### ISSUE TITLE
Inaccurate DTC Count

### ISSUE THREAD

**Issue by SOGAPPS** [kkonteh97/SwiftOBD2#25]
**Describe the bug**
DTC Count returns only 4 or 7 for two different cars. [BMW 328i 2016, BMW 325i 2006]

**To Reproduce**
1. Run SwiftOBD2App on Xcode
2. Go to 'VehicleDiagnosticsView'
3. Click on 'Scan'
4. Scroll down to 'complete'
5. See returned DTC count and description

**Expected behavior**
Should return 0 DTC for [BMW 328i 2016]
Should return 2 DTC for [BMW 325i 2006] ~ estimate based on previous return

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone SE]
- OS: [e.g. iOS 17.4.1]

**Additional context**
The DTC Descriptions look fine 

[BMW 328i 2016] Log values:
```
Getting status
Sending command: 0101
Response: ["7E8 06 41 01 00 07 E5 00 ", "7E9 06 41 01 00 04 00 00 "]
Status response: ["7E8 06 41 01 00 07 E5 00 ", "7E9 06 41 01 00 04 00 00 "]
Scanning for trouble codes
Sending command: 03
Response: ["7E8 02 43 00 ", "7E9 02 43 00 "]
```

[BMW 325i 2006] Log values:
```
Getting status
Sending command: 0101
Response: ["86 F1 18 41 01 00 04 00 00 D5 ", "86 F1 12 41 01 82 07 65 00 B9 "]
Status response: ["86 F1 18 41 01 00 04 00 00 D5 ", "86 F1 12 41 01 82 07 65 00 B9 "]
Scanning for trouble codes
Sending command: 03
Response: ["87 F1 18 43 00 00 00 00 00 00 D3 ", "87 F1 12 43 15 53 13 28 00 00 70 "]
```

**Comment by kkonteh97** [comment]
should be fixed now

**Comment by SOGAPPS** [comment]
> should be fixed now

It's resolved now. Thanks
